Feature/133 input values endpoint
Eastern-Research-Group/expert-query pull request #30
Opened 2022-12-16 18:56 UTC by maxdiebold-erg

## Related Issues:
* [EQ-133](https://jira.epa.gov/secure/RapidBoard.jspa?rapidView=865&view=detail&selectedIssue=EQ-133)

## Main Changes:
* Added a `values` endpoint to the internal API, used for populating inputs in the interface. This endpoint will return column values that match a case-insensitive `LIKE` clause up to a specified limit, and optionally filter the results by other `WHERE` clauses.
* Updated the select inputs in the interface to send a request to the endpoint if field values are not already present in the domain values or list values.

## Steps To Test:
1. Start the client application, then navigate to the home page: https://localhost:3000/attains.
2. In the **Data Profile** drop-down, select *Assessment Units*.
3. The **Assessment Unit ID** field and the **Location Text** field both retrieve their values from the database. Confirm that they are populated with 20 values by default, and that the list of values updates as characters are entered into the input's search box.
4. Confirm that the **Location Text** field values update properly when different sources are selected from the source drop-down.

2022-12-16 19:03 UTC, maxdiebold-erg commented
The values endpoint is currently crafted from two slugs (one for the profile, another for the column), in an attempt to mirror the structure of the endpoints on the `data` side. We could, however, just move it to a single `/data/values` endpoint, and put both the profile and column in the GET parameters.

Also, I didn't create a POST endpoint for the time being because this will only be used internally, GET requests are marginally faster, and there aren't many parameters.

2022-12-19 16:02 UTC, cschwinderg requested changes
Works well! 

I have one suggestion below.

2022-12-19 17:27 UTC, maxdiebold-erg commented on app/client/src/config/index.tsx
> +    : window.location.origin;
Oh, right!

2022-12-19 18:32 UTC, cschwinderg approved these changes
Thanks for making that change and fixing the merge conflicts.

2022-12-19 18:32 UTC, merged