Feature/204 swagger UI page
Eastern-Research-Group/expert-query pull request #76
Opened 2023-04-24 21:24 UTC by maxdiebold-erg

## Related Issues:
* [EQ-204](https://jira.epa.gov/browse/EQ-204)

## Main Changes:
* Added Swagger API documentation for the profile `/data` routes and there corresponding `/count` routes.
  * I left the contact email blank for now. Also most parameters still need descriptions, since we're still waiting on glossary/tooltip descriptions from EPA.
  * The configuration file is stored with the S3 content, so the filepath shown in the UI would be strange if displayed:
  
![swagger](https://user-images.githubusercontent.com/104089016/233712150-6db00e96-4c7a-4105-bf5e-1fb9862aba6c.png)

If we want this JSON file to be publicly accessible, we may need to move it to the `public` folder; currently, the link to the file is hidden.

## Steps To Test:
1. Go to the API docs page: http://localhost:3000/api-docs.
2. Confirm that all routes are properly documented, and that trying queries works as expected.

2023-04-25 16:06 UTC, cschwinderg requested changes
Looks good! I haven't looked to closely at the openapi file yet. 

Can you add a button next to the Glossary and National Downloads buttons that opens the api documentation?

Are you getting these console errors/warnings on your end when you run the app?
![image](https://user-images.githubusercontent.com/46329268/234336557-5bdea5b8-c63f-4863-aada-dc5bdd25b5ba.png)

2023-04-25 16:34 UTC, maxdiebold-erg commented on etl/app/content-private/domainValueMappings.json
> +    "valueField": "name"
Thanks!

2023-04-25 16:46 UTC, maxdiebold-erg commented
I am getting those warnings, I'll try checking those repositories to see if anybody else is having those issues.

2023-04-26 18:02 UTC, maxdiebold-erg commented
It looks like the warnings are due to the fact that the _Autolinker_ package is generating source maps when compiling their TypeScript source code, but they aren't including the source code in the NPM package (as raised in https://github.com/gregjacobs/Autolinker.js/issues/396 and discussed generally in https://github.com/facebook/create-react-app/discussions/11767). It doesn't look like there is a way to disable this warning for a particular package, but it would only become a problem when trying to debug _Autolinker_ code.

Both `swagger-ui` and `swagger-ui-react` include `remarkable` as a dependency, which includes `autolinker`, so I think the only way to avoid the warning would be to keep the bundles in the `public` folder, like LEW does, but that option is a lot heavier.

2023-04-26 20:48 UTC, cschwinderg commented
> Both `swagger-ui` and `swagger-ui-react` include `remarkable` as a dependency, which includes `autolinker`, so I think the only way to avoid the warning would be to keep the bundles in the `public` folder, like LEW does, but that option is a lot heavier.

 We may need to keep the bundles in the `public` folder just to cut down on the noise in the console. We can discuss this lader though. I'll go ahead and merge this in as is.

2023-04-26 20:49 UTC, cschwinderg approved these changes

2023-04-26 20:49 UTC, merged